platform :ios, '11.0'

target 'SelfSignedCert' do
  use_frameworks!

  pod 'IDZSwiftCommonCrypto'
  pod 'SwiftBytes'
  pod 'SecurityExtensions', :git => 'https://github.com/Adis/swift-SecurityExtensions.git'

  target 'SelfSignedCertTests' do
    pod 'Quick'
    pod 'Nimble'
  end

end
